# Generated by Django 4.2.1 on 2023-06-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slot',
        ),
    ]
