# Generated by Django 4.2.1 on 2023-06-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='userType',
        ),
    ]
