# Generated by Django 4.2.1 on 2023-06-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=350)),
                ('image', models.ImageField(null=True, upload_to='department/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('certificate', models.ImageField(null=True, upload_to='certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.department')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': False, 'is_superadmin': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
