# Generated by Django 4.2.1 on 2023-06-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='specialization',
            new_name='department',
        ),
    ]
