# Generated by Django 4.2.1 on 2023-06-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_specialization_doctors_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='is_approved',
        ),
    ]
