# Generated by Django 4.2.1 on 2023-06-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctors_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
