# Generated by Django 4.2.1 on 2023-06-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
