# Generated by Django 4.2.1 on 2023-06-24 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0005_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('doctor', models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': True, 'is_superadmin': False}, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors')),
                ('patient', models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': False, 'is_superadmin': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.slots')),
            ],
        ),
    ]
