# Generated by Django 4.2.1 on 2023-07-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_appointment_appointment_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_payment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
