# Generated by Django 4.2.1 on 2023-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_appointment_status_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
